- hosts: node
  become: true
  tasks:
     - name: delete old deployment
       command: kubectl delete -f /home/vagrant/Deployment.yaml
     - name: delete old service
       command: kubectl delete -f /home/vagrant/Service.yaml
     - name: create new deployment
       command: kubectl apply -f /home/vagrant/Deployment.yaml
     - name: create new service
       command: kubectl apply -f /home/vagrant/Service.yaml
